language: node_js
node_js:
- '10'
addons:
  sonarcloud:
    organization: moser-ss-github
    token:
      secure: UVqgnuOPEn3Q7KUdbeXKZDZ0PvATnRdeY8TDGzt9fpCwPfhs56X+bNx2btZBP1H4Va2s6IYJezeiBhHxqt85A+9FUsH/hrHF1q8h/rcNrcUfDrbVDMcxX99tzNc1vC1oIYGCGFG1uYYn9YEOxJ/yGf6xTbuPgeus0InkN+ck9dYB65LIjnTAMRVtdCS7j+cW+qROGphAJQ1UKrj85EelYDEN+rVsY205BOa4eDruJsaPhEAegK3Ap74QbasEpm5pUNIF84+V1ofFKRVIBZYFzTjAFCq/FFnqZqp0BQaHCaXj41OmMj62P2H+7p0UcPKvNk/gZ6sah8Vwj2t/2QQ1mxtu3KAwMobJQchjpI41gtp59P7BofdF0UwkQh3LqgIgn/fFQI8ywsz9aTyNZWrNp62q/Wd592Y+cRbbAaCov+NiLdC9BPH1A7ij20Xqmseld9np4bXGTUQs8h/CSTD67HhDPGbOodG+2pvQyVoBT1BvqnPgUfoyvB2wQln5si0QbyW3N72jatl9FXHbEKlG3pqoNOSh56bgr0h1zxuInBshkVpSuKpDY/viovIYhriLAyxJGbi0QIfdp3Y4FP5tQBrpeJBhdom/9Re7C8S9l8Og7V8RnN611es6JDXvfgrUUrC53GqpM/Ai6LTmn+CVZ8oa5wWixINxLycl1Q54YV0=
script:
- npm build
- npm run test
- sonar-scanner
