language: node_js
node_js:
  - "10"
addons:
  sonarcloud:
    organization: "moser-ss-github"
    token:
        secure: "tJcJSlGDXfZ5BWojzwkXa8kkHc5Be5e5ZirBgBeUvwdKcqk9G6cTo9jUHrqCue1BkDDgZkJo0UCoC48tkeX2C6ME+ptHFAhX9otYfuvdCmrCl23fIAHxbJB94lmDUD8gfnb38yKF+ZttpxkI9YDQ6Pn/4oGuMvQ5SbMsReX5nzLi9KenkCqU7Pq95psNRBkWKAht+vVgxM5rFB/DYHy1AIuVcsyUBH49BWCwqZ8RI0/4sEKludRI6N3XlXAW7z3qzIPrH8YmF1ZcHiIeFJnXEy3iv6OZKbnV1FtdCns/jCmGD7uvoiaAZc99kEL5dPQ0GvrjGS0al5H2+loElGEfaz7McY1Kd37BeR2RZGcddw+3gJzQrUswdmgo4eXzYX2pp8Hco32OzPUQp5v4WBsr2Yni0x5gW5IyJuxX0r+LOIuORQ+C7tefokEegOtGiy+hXER3XfGJqRbus4bfZX1r5Ciekovoe2W/J46UdBAVMaO3TN36pCzDy/XZUWQNzn0t1DLvr3ZqYr/13eJ06/zWSIzz58KdBxtin2hpTu1E79z4yFm0RDdPzXYjQQ1TYpj+qj9AzBJmAEjv58RaDi5rjdPqHYJwLHP0rlAUYAJWvVfj5iVzID1r+MGAdpKs6ERILR+65JrUK1i6j9n5eJ+OARC6ndW0IZalVYZxaKQi/lY="
script:
  - npm build
  - npm run test
  - sonar-scanner
